spring:
  mqtt:
    client:
      id: mqttId
    completionTimeout: 3000
    default:
      topic: /data/adas
    password: user1
    url: ws://127.0.0.1:8083/mqtt
    username: user1
server:
  port: 8081
